const db = require('../db')
const { Author, Publisher, Book } = require('../models')


db.on('error', console.error.bind(console, 'MongoDB connection error:'))

const main = async () => {

const alexandraBracken = await Author.find({name: 'Alexandra Bracken'})
const chuckHogan = await Author.find({name: 'Chuck Hogan'})
const guillermoDelToro = await Author.find({name: 'Guillermo del Toro'})
const tomPerotta = await Author.find({name: 'Tom Perotta'})
const johnKnowles = await Author.find({name: 'John Knowles'})
const jamesBaldwin = await Author.find({name: 'James Baldwin'})
const johnSteinbeck = await Author.find({name: 'John Steinbeck'})
const williamBurroughs = await Author.find({name: 'William S. Burroughs'})
const fyodorDostoyevsky = await Author.find({name: 'Fyodor Dostoyevsky'})
const sophocles = await Author.find({name: 'Sophocles'})
const homer = await Author.find({name: 'Homer'})
const jaroslavHasek = await Author.find({name: 'Jaroslav Hasek'})
const jkRowling = await Author.find({name: 'J.K. Rowling'})
const elenaFerrante = await Author.find({name: 'Elena Ferrante'})
const adamSilvera = await Author.find({name: 'Adam Silvera'})
const pauloCoelho = await Author.find({name: 'Paulo Coelho'})
const olivieBlake = await Author.find({name: 'Olivie Blake'})
const fScottFitzgerald = await Author.find({name: 'F. Scott Fitzgerald'})
const carsonMcCullers = await Author.find({name: 'Carson McCullers'})
const sigmundFreud = await Author.find({name: 'Sigmund Freud'})
const reneeDescartes = await Author.find({name: "Renee Descartes"})
const theodoreDreiser = await Author.find({name: "Theodore Dreiser"})
const sorenKierkegaard = await Author.find({name: "Soren Kierkegaard"})
const aristotle = await Author.find({name: "Aristotle"})
const janetMalcolm = await Author.find({name: "Janet Malcolm"})
const markTwain = await Author.find({name: "Mark Twain"})
const williamShakespeare = await Author.find({name: "William Shakespeare"})
const robertLouisStevenson = await Author.find({name: "Robert Louis Stevenson"})
const oscarWilde = await Author.find({name: "Oscar Wilde"})
const charlesDickens = await Author.find({name: "Charles Dickens"})
const williamFinnegan = await Author.find({name: "William Finnegan"})
const annPatchett = await Author.find({name: "Ann Patchett"})
const hermannHesse = await Author.find({name: "Hermann Hesse"})
const richardMatheson = await Author.find({name: "Richard Matheson"})
const edithWharton = await Author.find({name: "Edith Wharton"})
const michaelHerr = await Author.find({name: "Michael Herr"})
const alexKotlowitz = await Author.find({name: "Alex Kotlowitz"})
const emmaLarkin = await Author.find({name: "Emma Larkin"})
const changRaeLee = await Author.find({name: "Chang-Rae Lee"})
const annPetry = await Author.find({name: "Ann Petry"})
const anneFadiman = await Author.find({name: "Anne Fadiman"})
const megJay = await Author.find({name: "Meg Jay, PhD"})
const multipleAuthors = await Author.find({name: "Multiple Authors"})
const tyTashiro = await Author.find({name: "Ty Tashiro, PhD"})
const davidPerlmutter = await Author.find({name: "Dr. David Perlmutter"})
const satchinPanda = await Author.find({name: "Satchin Panda, PhD"})
const jennyOdell = await Author.find({name: "Jenny Odell"})
const davidBrooks = await Author.find({name: "David Brooks"})

const hyperion = await Publisher.find({name: 'Hyperion'})
const harperCollins = await Publisher.find({name: 'HarperCollins'})
const stMartinsPress = await Publisher.find({name: 'St. Martins Press'})
const scribner = await Publisher.find({name: 'Scribner'})
const penguinBooks = await Publisher.find({name: 'Penguin Books'})
const vintageBooks = await Publisher.find({name: 'Vintage Books'})
const scholastic = await Publisher.find({name: 'Scholastic'})
const europaEditions = await Publisher.find({name: 'Europa Editions'})
const tor = await Publisher.find({name: 'Tor'})
const marinerBooks = await Publisher.find({name: 'Mariner Books'})
const wwNorton = await Publisher.find({name: 'W.W. Norton & Company'})
const hackett = await Publisher.find({name: 'Hackett'})
const oxford = await Publisher.find({name: 'Oxford'})
const barnesAndNoble = await Publisher.find({name: 'Barnes and Noble'})
const bantam = await Publisher.find({name: 'Bantam'})
const modernLibrary = await Publisher.find({name: 'Modern Library'})
const anchorBooks = await Publisher.find({name: "Anchor"})
const riverheadBooks = await Publisher.find({name: "Riverhead Books"})
const fsg = await Publisher.find({name: "Farrar, Straus, and Giroux"})
const hachette = await Publisher.find({name: "Hachette"})
const harvardBusinessReview = await Publisher.find({name: "Harvard Business Review"})
const rodale = await Publisher.find({name: "Rodale Books"})
const melville = await Publisher.find({name: "Melville House"})

    const books = [
        {
            title: "Lore",
            author: alexandraBracken[0]._id,
            genre: "Fantasy",
            ISBN: 9781484799925,
            publisher: hyperion[0]._id,
            year_published: 2021,
            description: "As punishment for a past rebellion, nine Greek gods are forced to walk the earth as mortals.  They are hunted by the descendants of ancint blood-lines, all eager to kill a god and seize their divine power and immortality.",
            image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1594222283i/53375824.jpg',
            condition: "Good",
            is_classic: false
        },

        {
            title: "The Strain",
            author: chuckHogan[0]._id,
            genre: "Fiction",
            ISBN: 9780062344618,
            publisher: harperCollins[0]._id,
            year_published: 2009,
            description: "A terrifying contagion has come to New York, an unstoppable plague that will spread like an all-consuming wildfire - lethal, merciless, hungry...vampiric.",
            image: 'https://prodimage.images-bn.com/pimages/9780062068255_p0_v5_s1200x630.jpg',
            condition: "Good",
            is_classic: false
        },
        {
            title: "The Leftovers",
            author: tomPerotta[0]._id,
            genre: "Fiction",
            ISBN: 9780312358341,
            publisher: stMartinsPress[0]._id,
            year_published: 2011,
            description: "People have mysteriously vanished in the town of Mapleton. Is it the Rapture?",
            image: 'https://m.media-amazon.com/images/M/MV5BNTE3MDc1MjY4NV5BMl5BanBnXkFtZTgwMDg4MjQ4MTE@._V1_QL75_UX190_CR0,0,190,281_.jpg',
            condition: "Good",
            is_classic: false
        },
        {
            title: "The Leftovers",
            author: tomPerotta[0]._id,
            genre: "Fiction",
            ISBN: 9780312358341,
            publisher: stMartinsPress[0]._id,
            year_published: 2011,
            description: "People have mysteriously vanished in the town of Mapleton. Is it the Rapture?",
            image: 'https://m.media-amazon.com/images/M/MV5BNTE3MDc1MjY4NV5BMl5BanBnXkFtZTgwMDg4MjQ4MTE@._V1_QL75_UX190_CR0,0,190,281_.jpg',
            condition: "Good",
            is_classic: false
        },
        {
            title: "A Separate Peace",
            author: johnKnowles[0]._id,
            genre: "Fiction",
            ISBN: 9780743253970,
            publisher: scribner[0]._id,
            year_published: 1959,
            description: "Set at a boys' boarding school in New England during the early years of World War II, A Separate Peace is a harrowing and luminous parable of the dark side of adolescence.",
            image: 'https://m.media-amazon.com/images/I/71A9xCYqjSL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Another Country",
            author: jamesBaldwin[0]._id,
            genre: "Fiction",
            ISBN: 9780141186375,
            publisher: penguinBooks[0]._id,
            year_published: 1962,
            description: "A masterly story of desire, hatred and violence where desperate and dangerous characters betray, love, and test each other to the limit.",
            image: 'https://m.media-amazon.com/images/I/91zdzRZd-RL._UF1000,1000_QL80_.jpg',
            condition: "Fair",
            is_classic: true,
        },
        {
            title: "Giovanni's Room",
            author: jamesBaldwin[0]._id,
            genre: "Fiction",
            ISBN: 9780345806567,
            publisher: vintageBooks[0]._id,
            year_published: 1956,
            description: "Set in the 1950's Paris of American expatriatess, liaisons, and violence, a young man finds himself caught between desire and conventional morality.",
            image: 'https://m.media-amazon.com/images/I/61sJyHSvGRL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Go Tell It on the Mountain",
            author: jamesBaldwin[0]._id,
            genre: "Fiction",
            ISBN: 9780375701870,
            publisher: vintageBooks[0]._id,
            year_published: 1952,
            description: "A fourteen-year-old boy discovers the terms of his identity as the stepson of the minister of a storefront Pentecostal church in Harlem.",
            image: 'https://m.media-amazon.com/images/I/6114OFCLFYL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        }, 
         {
            title: "The Grapes of Wrath",
            author: johnSteinbeck[0]._id,
            genre: "Fiction",
            ISBN: 9780140186409,
            publisher: penguinBooks[0]._id,
            year_published: 1939,
            description: "The Joads are driven off their homestead and forced to travel west to the promised land of California.",
            image: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/The_Grapes_of_Wrath_%281939_1st_ed_cover%29.jpg',
            condition: "Poor",
            is_classic: true,
        },
        {
            title: "East of Eden",
            author: johnSteinbeck[0]._id,
            genre: "Fiction",
            ISBN: 9780140186390,
            publisher: penguinBooks[0]._id,
            year_published: 1952,
            description: "In California's Salinas Valley, generations of families helplessly reenact the fall of Adam and Eve and the poisonous rivalry of Cain and Abel.",
            image: 'https://m.media-amazon.com/images/I/81dK6hlbsnL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Junky",
            author: williamBurroughs[0]._id,
            genre: "Autobiography",
            ISBN: 9780141189826,
            publisher: penguinBooks[0]._id,
            year_published: 1953,
            description: "A largely autobiographical account of the constant cycle of drug dependency, cures, and relapses.",
            image: 'https://m.media-amazon.com/images/I/51am6w3Z32L._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Crime and Punishment",
            author: fyodorDostoyevsky[0]._id,
            genre: "Fiction",
            ISBN: 9780140449136,
            publisher: penguinBooks[0]._id,
            year_published: 1991,
            description: "Raskolnikov, a destitue and desperate former student, wanders through the slums of St. Petersburg and commits a random murder without remorse or regret.",
            image: 'https://m.media-amazon.com/images/I/51Vg24nKbPL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "The Three Theban Plays",
            author: sophocles[0]._id,
            genre: "Theater",
            ISBN: 978014044254,
            publisher: penguinBooks[0]._id,
            year_published: 1982,
            description: "Towering over the rest of Greek tragedy, these three plays are among the most enduring and timeless dramas ever written.",
            image: 'https://m.media-amazon.com/images/I/81OQtTY348L._AC_UF1000,1000_QL80_.jpg',
            condition: "Fair",
            is_classic: true,
        },
        {
            title: "The Odyssey",
            author: homer[0]._id,
            genre: "Fiction",
            ISBN: 9780140449112,
            publisher: penguinBooks[0]._id,
            year_published: 1946,
            description: "The epic tale of Odysseus and his ten-year journey home after the Trojan War.",
            image: 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1711957706i/1381.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "The Good Soldier Svejk",
            author: jaroslavHasek[0]._id,
            genre: "Fiction",
            ISBN: 9780140449914,
            publisher: penguinBooks[0]._id,
            year_published: 1973,
            description: "Good-natured and garrulous, Svejk becomes the Austrian army's most loyal Czech soldier when he is called up on the outbreak of the First World War.",
            image: 'https://m.media-amazon.com/images/I/61DI41pxVsL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Harry Potter and the Sorcerers Stone",
            author: jkRowling[0]._id,
            genre: "Fantasy",
            ISBN: 978059035342,
            publisher: scholastic[0]._id,
            year_published: 1997,
            description: "Harry Potter receieves a mysterious letter with an invitation to a wonderful place he never dreamed existed.  There he finds a great destiny that's been waiting for him.",
            image: 'https://m.media-amazon.com/images/I/81DI+BAN2SL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Harry Potter and the Chamber of Secrets",
            author: jkRowling[0]._id,
            genre: "Fantasy",
            ISBN: 9780439064864,
            publisher: scholastic[0]._id,
            year_published: 1999,
            description: "Harry Potter returns for his second year at Hogwarts.",
            image: 'https://m.media-amazon.com/images/I/91WqeCn-PxL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Harry Potter and the Prisoner of Azkaban",
            author: jkRowling[0]._id,
            genre: "Fantasy",
            ISBN: 9780439136358,
            publisher: scholastic[0]._id,
            year_published: 1999,
            description: "For twelve years, Azkaban held an infamous prisoner named Sirius Black.  Now he has escaped, leaving only two clues as to where he might be headed.",
            image: 'https://m.media-amazon.com/images/I/812CcFkEPCL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Harry Potter and the Goblet of Fire",
            author: jkRowling[0]._id,
            genre: "Fantasy",
            ISBN: 9780439139595,
            publisher: scholastic[0]._id,
            year_published: 2000,
            description: "Harry mysteriously enters a dangerous and deadly international magic competition.",
            image: 'https://m.media-amazon.com/images/I/91-LL7OnDCL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Harry Potter and the Order of the Phoenix",
            author: jkRowling[0]._id,
            genre: "Fantasy",
            ISBN: 9780439358064,
            publisher: scholastic[0]._id,
            year_published: 2003,
            description: "Harry Potter is faced with the unreliability of the very government of the magical world and the impotence of the authorities at Hogwarts.",
            image: 'https://m.media-amazon.com/images/I/71pgI2ou5oL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "My Brilliant Friend",
            author: elenaFerrante[0]._id,
            genre: "Fiction",
            ISBN: 9781609450786,
            publisher: europaEditions[0]._id,
            year_published: 2012,
            description: "Book one of the Neapolitan Novels.  The story of Elena and Lila begins in the 1950s in a poor but vibrant neighborhood on the outskirts of Naples.",
            image: 'https://m.media-amazon.com/images/I/81p2bM1JNcL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "The Story of a New Name",
            author: elenaFerrante[0]._id,
            genre: "Fiction",
            ISBN: 9781609451349,
            publisher: europaEditions[0]._id,
            year_published: 2012,
            description: "Book two of the Neapolitan Novels.  Lila has recently married and made her entree into the familiy business. Elena continues her studies and her exploration of the world beyond the neighborhood.",
            image: 'https://m.media-amazon.com/images/I/81p2bM1JNcL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Those Who Leave and Those Who Stay",
            author: elenaFerrante[0]._id,
            genre: "Fiction",
            ISBN: 97816094452339,
            publisher: europaEditions[0]._id,
            year_published: 2013,
            description: "Book three of the Neapolitan Novels.  Set in the late 1960s and the 1970s, Those Who Leave and Those Who Stay continues the story of Lila and Elena.",
            image: 'https://m.media-amazon.com/images/I/81p2bM1JNcL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "The Story of the Lost Child",
            author: elenaFerrante[0]._id,
            genre: "Fiction",
            ISBN: 9781609452865,
            publisher: europaEditions[0]._id,
            year_published: 2015,
            description: "Book four of the Neapolitan Novels.  The concluding volume in the dazzling saga of two women.",
            image: 'https://m.media-amazon.com/images/I/81p2bM1JNcL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "They Both Die at the End",
            author: adamSilvera[0]._id,
            genre: "Fiction",
            ISBN: 9780062457806,
            publisher: harperCollins[0]._id,
            year_published: 2017,
            description: "On September 5, a little after midnight, Death-Cast calls Mateo Torrez and Rufus Emeterio to deliver some bad news: they're going to die in less than twenty-four hours.",
            image: 'https://bookoutlet.com/_next/image?url=https%3A%2F%2Fimages.bookoutlet.com%2Fcovers%2Flarge%2Fisbn978006%2F9780063274112-l.jpg&w=640&q=75',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "The Alchemist",
            author: pauloCoelho[0]._id,
            genre: "Fiction",
            ISBN: 9780061122415,
            publisher: harperCollins[0]._id,
            year_published: 1993,
            description: "An Andalusian shepherd boy travels to Egypt to seek a treasure buried beneath the Pyramids.",
            image: 'https://m.media-amazon.com/images/I/71NpZx6bmtL.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Masters of Death",
            author: olivieBlake[0]._id,
            genre: "Fantasy",
            ISBN: 9781250892461,
            publisher: tor[0]._id,
            year_published: 2018,
            description: "There is a game that the immortals play.  There is only one rule: don't lose.",
            image: 'https://m.media-amazon.com/images/I/81GCb6CIOSL._UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },     
           {
            title: "The Great Gatsby",
            author: fScottFitzgerald[0]._id,
            genre: "Fiction",
            ISBN: 9780743273565,
            publisher: scribner[0]._id,
            year_published: 1925,
            description: "The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
            image: 'https://m.media-amazon.com/images/I/81QuEGw8VPL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Naked Lunch",
            author: williamBurroughs[0]._id,
            genre: "Fiction",
            ISBN: 9780007341900,
            publisher: harperCollins[0]._id,
            year_published: 1959,
            description: "An exhilerating ride into the darkest recesses of the human psyche.",
            image: 'https://m.media-amazon.com/images/I/61DGofpvUhL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "The Member of the Wedding",
            author: carsonMcCullers[0]._id,
            genre: "Fiction",
            ISBN: 9780618492398,
            publisher: marinerBooks[0]._id,
            year_published: 1946,
            description: "The story f the imitable twelve-year-old Frankie, who is utterly, hopelessly bored with life until she hears about her older brother's upcoming wedding.",
            image: 'https://m.media-amazon.com/images/I/51ofy9P2xdL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Civilization and Its Discontents",
            author: sigmundFreud[0]._id,
            genre: "Philosophy",
            ISBN: 9780393301588,
            publisher: wwNorton[0]._id,
            year_published: 1961,
            description: "A brilliant summary of Freud's views on culture from a psycho-analytic perspective.",
            image: 'https://sdi4.chrislands.com/sdi/978/03/93/3/9780393301588.jpg',
            condition: "Fair",
            is_classic: true,
        },
        {
            title: "Discourse on Method and Meditations on First Philosophy",
            author: reneeDescartes[0]._id,
            genre: "Philosophy",
            ISBN: 9780872204201,
            publisher: hackett[0]._id,
            year_published: 1998,
            description: "A philosophical basis for constructing a new system of knowledge.",
            image: 'https://m.media-amazon.com/images/I/61z15m6mCpL._UF1000,1000_QL80_.jpg',
            condition: "Fair",
            is_classic: false,
        },
        {
            title: "Sister Carrie",
            author: theodoreDreiser[0]._id,
            genre: "Fiction",
            ISBN: 9780199539086,
            publisher: oxford[0]._id,
            year_published: 1900,
            description: "When a girl leaves her home at eighteen, she does one of two things. Either she falls into saving hands and becomes better, or she rapidly assumes the cosmopolitan standards of virtue and becomes worse.",
            image: 'https://m.media-amazon.com/images/I/71Z0imEm67L._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Fear and Trembling",
            author: sorenKierkegaard[0]._id,
            genre: "Philosophy",
            ISBN: 978014044490,
            publisher: penguinBooks[0]._id,
            year_published: 1985,
            description: "Writing under the pseudonym of Johannes de silentio, Kierkegaard uses the form of a dialectical lyric to present his conception of faith.",
            image: 'https://m.media-amazon.com/images/I/51Gz75cqtXL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "The Nicomachean Ethics",
            author: aristotle[0]._id,
            genre: "Philosophy",
            ISBN: 9780192834072,
            publisher: oxford[0]._id,
            year_published: 1925,
            description: "Aristotle sets out to discover the good life for man: the life of happiness.",
            image: 'https://m.media-amazon.com/images/I/61bDIEPTfqL.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "The Journalist and the Murderer",
            author: janetMalcolm[0]._id,
            genre: "Journalism",
            ISBN: 9780679731832,
            publisher: vintageBooks[0]._id,
            year_published: 1990,
            description: "Using the lawsuit of Jeffrey MacDonald, a convicted murderer, against Joe McGinniss, the author of Fatal Vision, a book about the crime, Malcolm delves into the relationship that exists between journalist and subject.",
            image: 'https://m.media-amazon.com/images/I/510-i6bA26L._AC_UF1000,1000_QL80_.jpg',
            condition: "Fair",
            is_classic: false,
        },
        {
            title: "The Adventures of Huckleberry Finn",
            author: markTwain[0]._id,
            genre: "Fiction",
            ISBN: 9781566192941,
            publisher: barnesAndNoble[0]._id,
            year_published: 1996,
            description: "Two runaways adventure down the Mississippi River on a raft.",
            image: 'https://target.scene7.com/is/image/Target/GUEST_7ed9384b-431e-4ef7-b1f5-ce1c5a4a2346?wid=488&hei=488&fmt=pjpeg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "A Midsummer Nights Dream",
            author: williamShakespeare[0]._id,
            genre: "Theater",
            ISBN: 9780198328667,
            publisher: oxford[0]._id,
            year_published: 1997,
            description: "Lovers and workmen of ancinet Athens enter the fairy realm and soon become aware of the strangeness of their surroundings.",
            image: 'https://thebaronsmen.org/site/assets/files/2101/71e6ouzedwl.jpg',
            condition: "Fair",
            is_classic: true,
        },
        {
            title: "Treasure Island",
            author: robertLouisStevenson[0]._id,
            genre: "Fiction",
            ISBN: 9780439288886,
            publisher: scholastic[0]._id,
            year_published: 2001,
            description: "When Jim Hawkins finds an old pirate map showing a small island marked with a red cross, he knows that a fortune in gold lies waiting for him.",
            image: 'https://d28hgpri8am2if.cloudfront.net/book_images/cvr9781416500292_9781416500292_hr.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "The Picture of Dorian Gray",
            author: oscarWilde[0]._id,
            genre: "Fantasy",
            ISBN: 9780553212549,
            publisher: bantam[0]._id,
            year_published: 1982,
            description: "The story of Dorian Gray, a wealthy young Englishman who prizes his looks and youth, and is hiding a secret.",
            image: 'https://m.media-amazon.com/images/I/41XYp5hDDBL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Great Expectations",
            author: charlesDickens[0]._id,
            genre: "Fiction",
            ISBN: 9780451526716,
            publisher: penguinBooks[0]._id,
            year_published: 1961,
            description: "The orphan Pip, the convict Magwitch, the beautiful Estella, the vengeful Miss Havisham, the strangely ambiguous figure of the master lawyer Mr. Jaggers, all play their part in a story about the Victorian middle class.",
            image: 'https://images.booksense.com/images/132/726/9781532726132.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "Cold New World",
            author: williamFinnegan[0]._id,
            genre: "Journalism",
            ISBN: 9780375753824,
            publisher: modernLibrary[0]._id,
            year_published: 1998,
            description: "New Yorker writer William Finnegan spent time with families in four communities across America and became an intimate observer of the lives he reveals in these beautifully rendered portraits.",
            image: 'https://images.penguinrandomhouse.com/cover/9780375753824',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Run",
            author: annPatchett[0]._id,
            genre: "Fiction",
            ISBN: 9780061340642,
            publisher: harperCollins[0]._id,
            year_published: 2007,
            description: "Since their mother's death, Tip and Teddy Doyle have been raised by their loving, possessive, and ambitious father.",
            image: 'https://m.media-amazon.com/images/I/51Jg4tat5iL._UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Demian",
            author: hermannHesse[0]._id,
            genre: "Fiction",
            ISBN: 9780060931919,
            publisher: harperCollins[0]._id,
            year_published: 1925,
            description: "The descent of Emil Sinclair, led by a precocious schoolmate Max Demian, into a secret and dangerous world of petty crime and revolt against convention and eventual awakening into selfhood.",
            image: 'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1175556544l/528762.jpg',
            condition: "Fair",
            is_classic: true,
        },
        {
            title: "I Am Legend",
            author: richardMatheson[0]._id,
            genre: "Fiction",
            ISBN: 9780765318749,
            publisher: tor[0]._id,
            year_published: 1995,
            description: "Robert Neville may well be the only survivor of an incurable plague that has mutated every other man, woman, and child into bloodthirsty, nocturnal creatures who are determined to destroy him.",
            image: 'https://m.media-amazon.com/images/I/71mJuUVBeIL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "The Age of Innocence",
            author: edithWharton[0]._id,
            genre: "Fiction",
            ISBN: 9780451530882,
            publisher: penguinBooks[0]._id,
            year_published: 1920,
            description: "Young Lawyer Newland Archer believes that he must make an impossible choice: domesticity with his docile and lovely fiancee, or passion with her highly unsuitable but irresistible cousin.",
            image: 'https://images.penguinrandomhouse.com/cover/9780451530882',
            condition: "Good",
            is_classic: true,
        },
        {
            title: "On Booze",
            author: fScottFitzgerald[0]._id,
            genre: "Fiction",
            ISBN: 9780811219266,
            publisher: scribner[0]._id,
            year_published: 1931,
            description: "Gathering debutantes and dandies, rowdy jazz musicians, lost children and ragtime riffraff, On Booze runs a gauntlet of drunken debauchery.",
            image: 'https://m.media-amazon.com/images/I/41vHzk6mV0L._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Dispatches",
            author: michaelHerr[0]._id,
            genre: "Journalism",
            ISBN: 9780679735259,
            publisher: vintageBooks[0]._id,
            year_published: 1968,
            description: "With uncanny precision, Herr summons up the very essence of the Vietnam War.",
            image: 'https://m.media-amazon.com/images/I/41v0Ckz825L._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "There Are No Children Here",
            author: alexKotlowitz[0]._id,
            genre: "Journalism",
            ISBN: 9780385265565,
            publisher: anchorBooks[0]._id,
            year_published: 1991,
            description: "A meticulous portrait of two boys in a Chicago housing project.",
            image: 'https://m.media-amazon.com/images/I/71W1TmVt03L._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Finding George Orwell in Burma",
            author: emmaLarkin[0]._id,
            genre: "Journalism",
            ISBN: 9780143037118,
            publisher: penguinBooks[0]._id,
            year_published: 2004,
            description: "Emma Larkin tells of the year she spent traveling through Burma. She provides a powerful reckoning with one of the world's least free countries.",
            image: 'https://m.media-amazon.com/images/I/81+J0d0FB8L._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Native Speaker",
            author: changRaeLee[0]._id,
            genre: "Fiction",
            ISBN: 9781573225311,
            publisher: riverheadBooks[0]._id,
            year_published: 1995,
            description: "Henry is forever uncertain of his place, a perpatual outsider looking at American culture from a distance.",
            image: 'https://m.media-amazon.com/images/I/617MSyBY9eL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "The Street",
            author: annPetry[0]._id,
            genre: "Fiction",
            ISBN: 9780395901496,
            publisher: marinerBooks[0]._id,
            year_published: 1946,
            description: "The story of Lutie Johnson, a young black woman, and her spirited struggle to raise her son amid the violence, poverty, and racial dissonance of Harlem in the late 1940s.",
            image: 'https://m.media-amazon.com/images/I/71XWlxfEgrL._AC_UF350,350_QL50_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "The Spirit Catches You and You Fall Down",
            author: anneFadiman[0]._id,
            genre: "Journalism",
            ISBN: 9780374525644,
            publisher: fsg[0]._id,
            year_published: 1997,
            description: "Lia's parents and her doctors both wanted what was best for Lia, but the lack of understanding between them led to tragedy.",
            image: 'https://m.media-amazon.com/images/I/71b2Gl9TIUL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "The Defining Decade",
            author: megJay[0]._id,
            genre: "Self-Help",
            ISBN: 9780446561761,
            publisher: hachette[0]._id,
            year_published: 2012,
            description: "New insights about the twentysomething yeras and how they shape our lives.",
            image: 'https://m.media-amazon.com/images/I/812pT1QRzUL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "On Managing Yourself",
            author: multipleAuthors[0]._id,
            genre: "Self-Help",
            ISBN: 9781422157992,
            publisher: harvardBusinessReview[0]._id,
            year_published: 2010,
            description: "If you read nothing else on managing yourself, read these 10 articles.",
            image: 'https://m.media-amazon.com/images/I/71sxhdNwA8L._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Awkward: The Science of Why We're Socially Awkward and Why That's Awesome",
            author: tyTashiro[0]._id,
            genre: "Self-Help",
            ISBN: 9780062429155,
            publisher: harperCollins[0]._id,
            year_published: 2017,
            description: "Full of moving stories and chock-full of research, Awkward offers awkward and non-awkward people alike insight into have better relationships and lead richer lives.",
            image: 'https://m.media-amazon.com/images/I/71uQwdNKOHL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Grain Brain",
            author: davidPerlmutter[0]._id,
            genre: "Self-Help",
            ISBN: 9781473695580,
            publisher: hachette[0]._id,
            year_published: 2014,
            description: "Featuring the latest data and practical advice, Grain Brain empowers you to take control of your health like never before.",
            image: 'https://images-na.ssl-images-amazon.com/images/I/71acxZZgtDL._AC_UL210_SR210,210_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "Drop Acid",
            author: davidPerlmutter[0]._id,
            genre: "Self-Help",
            ISBN: 9781529388435,
            publisher: hachette[0]._id,
            year_published: 2022,
            description: "Bestselling author Dr. Davit Perlmutter offers dietary and lifestyle tweaks to help you lose weight, prevent and reverse disease, and live a long, healthy life by reducing high uric acid levels.",
            image: 'https://m.media-amazon.com/images/I/71Hvsqvcu4L.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "The Circadian Code",
            author: satchinPanda[0]._id,
            genre: "Self-Help",
            ISBN: 9780593135907,
            publisher: rodale[0]._id,
            year_published: 2018,
            description: "The Circadian Code is a revolution in the way you think about diet, exercise, work, learning, and technology.",
            image: 'https://m.media-amazon.com/images/I/715Ef1hh5yL._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "How to Do Nothing",
            author: jennyOdell[0]._id,
            genre: "Self-Help",
            ISBN: 9781612197494,
            publisher: melville[0]._id,
            year_published: 2019,
            description: "Nothing is harder to do these days than nothing. But in a world where our value is determined by our 24/7 data productivity, doing nothing may be our most important form of resistance.",
            image: 'https://images.penguinrandomhouse.com/cover/9781612198552',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "How to Do Nothing",
            author: jennyOdell[0]._id,
            genre: "Self-Help",
            ISBN: 9781612197494,
            publisher: melville[0]._id,
            year_published: 2019,
            description: "Nothing is harder to do these days than nothing. But in a world where our value is determined by our 24/7 data productivity, doing nothing may be our most important form of resistance.",
            image: 'https://images.penguinrandomhouse.com/cover/9781612198552',
            condition: "Good",
            is_classic: false,
        },
        {
            title: "How to Know A Person",
            author: davidBrooks[0]._id,
            genre: "Self-Help",
            ISBN: 9780241670293,
            publisher: penguinBooks[0]._id,
            year_published: 2023,
            description: "Brooks draws from psychology, neuroscience, theatre, philosophy, history, and education to present a practical, hopeful approach to human connection.",
            image: 'https://m.media-amazon.com/images/I/81Gvt3v-J3L._AC_UF1000,1000_QL80_.jpg',
            condition: "Good",
            is_classic: false,
        },


    ]

    await Book.insertMany(books)
    console.log("Created some books!")
}
const run = async () => {
    await main()
    db.close()
}

run()